# Generated by Django 3.0.5 on 2021-01-03 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='chat_id',
            field=models.CharField(default='cf4aeae1-cda7-41f3-adf7-9b2bb377be7d', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='idea',
            name='notes',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='lab',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
