# Generated by Django 3.1.7 on 2021-03-22 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210320_2327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labmember',
            name='isAdmin',
        ),
        migrations.AddField(
            model_name='lab',
            name='code',
            field=models.CharField(default='a1234', max_length=55),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='LabJoin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=20)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lab')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
