# Generated by Django 3.1.7 on 2021-03-27 02:13

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210321_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='labjoin',
            name='accepted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_join_accepted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labjoin',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lab',
            name='code',
            field=models.CharField(default=core.models.random_code, max_length=55, unique=True),
        ),
        migrations.AlterField(
            model_name='labjoin',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_join_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
