# Generated by Django 3.1.7 on 2021-03-28 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210326_2249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lab',
            options={'permissions': (('core.lab_view', 'lab view'), ('core.lab_create', 'lab create'), ('core.lab_modify', 'lab modify'), ('core.lab_delete', 'lab delete'))},
        ),
        migrations.AlterModelOptions(
            name='labjoin',
            options={'permissions': (('core.lab_join_delete', 'lab join delete'), ('core.lab_join_modify', 'lab join modify'))},
        ),
    ]
