# Generated by Django 3.1.7 on 2021-03-28 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210328_1636'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lab',
            options={'permissions': (('lab_join_delete', 'lab join delete'), ('lab_join_modify', 'lab join modify'), ('lab_view', 'lab view'), ('lab_create', 'lab create'), ('lab_modify', 'lab modify'), ('lab_delete', 'lab delete'))},
        ),
        migrations.AlterModelOptions(
            name='labjoin',
            options={},
        ),
    ]
