# Generated by Django 3.1.7 on 2021-04-01 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210328_1837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labjoin',
            old_name='accepted_by',
            new_name='handled_by',
        ),
        migrations.RemoveField(
            model_name='labjoin',
            name='is_accepted',
        ),
    ]
