# Generated by Django 3.2 on 2021-09-25 09:03

import core.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210401_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='code',
            field=models.CharField(db_index=True, default=core.models.random_code, max_length=55, unique=True),
        ),
        migrations.AlterField(
            model_name='lab',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='labjoin',
            name='created_by',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.user'),
            preserve_default=False,
        ),
    ]
