# Generated by Django 3.2 on 2021-09-25 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210925_0403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labmember',
            old_name='is_admin',
            new_name='is_lab_admin',
        ),
    ]
